addons:
    apt:
        update: true


language: c++


before_install:
    - sudo apt update

install:
    - ls
    - pwd
    - sudo apt install valgrind
    - sudo apt install cmake
    - sudo apt-get install clang-format
    - git clone https://github.com/nlohmann/json
    - cd json
    - cmake .
    - sudo make install
    - sudo apt-get install lcov
    - sudo apt-get install libgtest-dev
    - sudo apt-get install libsfml-dev
    - sudo apt-get install libboost-all-dev
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo cp *.a /usr/lib
    - cd /home/travis/build/While-true-Technopark/BaumanRacing

before_script:
    - cd server
    - cmake .
    - make
    - cd -

after_script:
    - make clean